modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="purgatory"
version="1.0.0"
displayName="Purgatory"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="Denus, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.purgatory]]
modId="neoforge"
type="required"
versionRange="[21.1.65,)"
ordering="AFTER"
side="BOTH"

[[dependencies.purgatory]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="AFTER"
side="BOTH"


[[dependencies.purgatory]]
modId="geckolib"
type="optional"
versionRange="[0,)"
ordering="NONE"
side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration